version: '3.7'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d:ro
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

  myapp:
    depends_on:
      - mysql
    image: openjdk:11.0.13-slim
    volumes:
      - ./artifacts:/artifacts
    ports:
      - '9999:9999'
    command: bash -c "sleep 30 && java -jar ./artifacts/app-deadline.jar -P:jdbc.url=jdbc:mysql://host.docker.internal:3306/mydb -P:jdbc.user=user -P:jdbc.password=pass"



